# Site Info
title: Jangwon Dev Blog
tagline: '개발 블로그 & 저장소'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: https://dev-jangwon.github.io/
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jangwon Kim
  description: Hello:)
    # Want to be a
    #     <span class="codinfox-changing-keywords">
    #         <b class="visible">Developer</b>
    #         <b class="hidden">Confident man</b>
    #         <b class="hidden">Lifelong learner</b>
    #     </span><br>
  gravatar: 40e53960ce70ab8a540f73df713560d9 # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/dev-jangwon
    facebook:  https://www.facebook.com/jangwon.kim.54
    # twitter:   https://twitter.com/Li_Zhihao
    # weibo:     http://weibo.com/41173780
    email:     http://www.google.com/recaptcha/mailhide/d?k=011C7mvSQVAkNDWV2c7kKMfg==&c=LKR96jp7I9p69Llq-Ep6EV1d1U8x7uLIUjyf9hYNQMY=

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'https://github.com/dev-jangwon'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

cover_image:
  image: /public/img/wenger.jpg
  caption: a naive optimist

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'dev-jangwon'
